-- 0002_seed_sources.sql
-- GENERATED by `just gen-source-artifacts` from src/source_registry (Rust).
-- DO NOT EDIT BY HAND. Drift from the registry fails CI.
--
-- Seeds every `source` row from the Source Lifecycle Registry in registry
-- order, so `source.id` (GENERATED ALWAYS AS IDENTITY) is assigned 1..N in
-- that order. This is a registry-generated BASELINE seed that replaces the
-- previously scattered per-source seed migrations; it requires a fresh /
-- reset database. See migrations/README.md (source-registry baseline reset).
--
-- The fail-fast guard below raises if `source` is already populated, so an
-- accidental in-place run on an un-reset database aborts cleanly (the
-- migrate-safe backup stays intact) instead of appending rows with wrong ids.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM source) THEN
        RAISE EXCEPTION 'source table is not empty: 0002_seed_sources is a registry-generated baseline seed that requires a fresh / reset database (see migrations/README.md, source-registry baseline reset).';
    END IF;
END;
$$;

ALTER TABLE source ALTER COLUMN id RESTART WITH 1;

INSERT INTO source (code, kind, chain, instance, created_at)
VALUES
    ('auxpow:namecoin', 'auxpow', 'namecoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:rsk', 'auxpow', 'rsk', NULL, extract(epoch from now())::bigint),
    ('live-chaintip:bitcoin:core', 'live-chaintip', 'bitcoin', 'core', extract(epoch from now())::bigint),
    ('auxpow:syscoin', 'auxpow', 'syscoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:fractal', 'auxpow', 'fractal', NULL, extract(epoch from now())::bigint),
    ('auxpow:hathor', 'auxpow', 'hathor', NULL, extract(epoch from now())::bigint),
    ('auxpow:elastos', 'auxpow', 'elastos', NULL, extract(epoch from now())::bigint),
    ('auxpow:argentum', 'auxpow', 'argentum', NULL, extract(epoch from now())::bigint),
    ('auxpow:bitcoin-vault', 'auxpow', 'bitcoin-vault', NULL, extract(epoch from now())::bigint),
    ('auxpow:bitmark', 'auxpow', 'bitmark', NULL, extract(epoch from now())::bigint),
    ('auxpow:coiledcoin', 'auxpow', 'coiledcoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:crown', 'auxpow', 'crown', NULL, extract(epoch from now())::bigint),
    ('auxpow:devcoin', 'auxpow', 'devcoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:emercoin', 'auxpow', 'emercoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:geistgeld', 'auxpow', 'geistgeld', NULL, extract(epoch from now())::bigint),
    ('auxpow:groupcoin', 'auxpow', 'groupcoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:huntercoin', 'auxpow', 'huntercoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:i0coin', 'auxpow', 'i0coin', NULL, extract(epoch from now())::bigint),
    ('auxpow:ixcoin', 'auxpow', 'ixcoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:myriadcoin', 'auxpow', 'myriadcoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:terracoin', 'auxpow', 'terracoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:unobtanium', 'auxpow', 'unobtanium', NULL, extract(epoch from now())::bigint),
    ('auxpow:xaya', 'auxpow', 'xaya', NULL, extract(epoch from now())::bigint),
    ('auxpow:vcash', 'auxpow', 'vcash', NULL, extract(epoch from now())::bigint),
    ('auxpow:lyncoin', 'auxpow', 'lyncoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:jax-network', 'auxpow', 'jax-network', NULL, extract(epoch from now())::bigint),
    ('auxpow:sixeleven', 'auxpow', 'sixeleven', NULL, extract(epoch from now())::bigint),
    ('auxpow:blast', 'auxpow', 'blast', NULL, extract(epoch from now())::bigint),
    ('auxpow:doichain', 'auxpow', 'doichain', NULL, extract(epoch from now())::bigint),
    ('auxpow:fusioncoin', 'auxpow', 'fusioncoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:jincoin', 'auxpow', 'jincoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:mazacoin', 'auxpow', 'mazacoin', NULL, extract(epoch from now())::bigint),
    ('auxpow:bitcoin-stash', 'auxpow', 'bitcoin-stash', NULL, extract(epoch from now())::bigint),
    ('auxpow:elcash', 'auxpow', 'elcash', NULL, extract(epoch from now())::bigint);
