-- 0002_seed_sources.sql
-- GENERATED by `just gen-source-artifacts` from src/source_registry (Rust).
-- DO NOT EDIT BY HAND. Drift from the registry fails CI.
--
-- Seeds every `source` row from the Source Lifecycle Registry using its
-- explicit permanent ids. Ids may have gaps and are never reused. This
-- registry-generated BASELINE seed replaces the previously scattered
-- per-source seed migrations; it requires a fresh / reset database. See
-- migrations/README.md (source-registry baseline reset).
--
-- The fail-fast guard below raises if `source` is already populated, so an
-- accidental in-place run on an un-reset database aborts cleanly (the
-- migrate-safe backup stays intact) instead of appending rows with wrong ids.

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM source) THEN
        RAISE EXCEPTION 'source table is not empty: 0002_seed_sources is a registry-generated baseline seed that requires a fresh / reset database (see migrations/README.md, source-registry baseline reset).';
    END IF;
END;
$$;

INSERT INTO source (id, code, kind, chain, instance, created_at)
OVERRIDING SYSTEM VALUE
VALUES
    (1, 'auxpow:namecoin', 'auxpow', 'namecoin', NULL, extract(epoch from now())::bigint),
    (2, 'auxpow:rsk', 'auxpow', 'rsk', NULL, extract(epoch from now())::bigint),
    (3, 'live-chaintip:bitcoin:core', 'live-chaintip', 'bitcoin', 'core', extract(epoch from now())::bigint),
    (4, 'auxpow:syscoin', 'auxpow', 'syscoin', NULL, extract(epoch from now())::bigint),
    (5, 'auxpow:fractal', 'auxpow', 'fractal', NULL, extract(epoch from now())::bigint),
    (6, 'auxpow:hathor', 'auxpow', 'hathor', NULL, extract(epoch from now())::bigint),
    (7, 'auxpow:elastos', 'auxpow', 'elastos', NULL, extract(epoch from now())::bigint),
    (8, 'auxpow:argentum', 'auxpow', 'argentum', NULL, extract(epoch from now())::bigint),
    (9, 'auxpow:bitcoin-vault', 'auxpow', 'bitcoin-vault', NULL, extract(epoch from now())::bigint),
    (10, 'auxpow:bitmark', 'auxpow', 'bitmark', NULL, extract(epoch from now())::bigint),
    (11, 'auxpow:coiledcoin', 'auxpow', 'coiledcoin', NULL, extract(epoch from now())::bigint),
    (12, 'auxpow:crown', 'auxpow', 'crown', NULL, extract(epoch from now())::bigint),
    (13, 'auxpow:devcoin', 'auxpow', 'devcoin', NULL, extract(epoch from now())::bigint),
    (14, 'auxpow:emercoin', 'auxpow', 'emercoin', NULL, extract(epoch from now())::bigint),
    (15, 'auxpow:geistgeld', 'auxpow', 'geistgeld', NULL, extract(epoch from now())::bigint),
    (16, 'auxpow:groupcoin', 'auxpow', 'groupcoin', NULL, extract(epoch from now())::bigint),
    (17, 'auxpow:huntercoin', 'auxpow', 'huntercoin', NULL, extract(epoch from now())::bigint),
    (18, 'auxpow:i0coin', 'auxpow', 'i0coin', NULL, extract(epoch from now())::bigint),
    (19, 'auxpow:ixcoin', 'auxpow', 'ixcoin', NULL, extract(epoch from now())::bigint),
    (20, 'auxpow:myriadcoin', 'auxpow', 'myriadcoin', NULL, extract(epoch from now())::bigint),
    (21, 'auxpow:terracoin', 'auxpow', 'terracoin', NULL, extract(epoch from now())::bigint),
    (22, 'auxpow:unobtanium', 'auxpow', 'unobtanium', NULL, extract(epoch from now())::bigint),
    (23, 'auxpow:xaya', 'auxpow', 'xaya', NULL, extract(epoch from now())::bigint),
    (24, 'auxpow:vcash', 'auxpow', 'vcash', NULL, extract(epoch from now())::bigint),
    (25, 'auxpow:lyncoin', 'auxpow', 'lyncoin', NULL, extract(epoch from now())::bigint),
    (26, 'auxpow:jax-network', 'auxpow', 'jax-network', NULL, extract(epoch from now())::bigint),
    (27, 'auxpow:sixeleven', 'auxpow', 'sixeleven', NULL, extract(epoch from now())::bigint),
    (28, 'auxpow:blast', 'auxpow', 'blast', NULL, extract(epoch from now())::bigint),
    (29, 'auxpow:doichain', 'auxpow', 'doichain', NULL, extract(epoch from now())::bigint),
    (30, 'auxpow:fusioncoin', 'auxpow', 'fusioncoin', NULL, extract(epoch from now())::bigint),
    (31, 'auxpow:jincoin', 'auxpow', 'jincoin', NULL, extract(epoch from now())::bigint),
    (33, 'auxpow:bitcoin-stash', 'auxpow', 'bitcoin-stash', NULL, extract(epoch from now())::bigint),
    (34, 'auxpow:elcash', 'auxpow', 'elcash', NULL, extract(epoch from now())::bigint);

ALTER TABLE source ALTER COLUMN id RESTART WITH 35;
