-- 0005_rename_excluded_orphan_class.sql
--
-- Renames the `btc_orphan_class` excluded verdict token from
-- `btc_stale_excluded` to `excluded`, in lockstep with the same rename in the
-- merge-mining-research repo's `btc_stale_relevance` vocabulary (the shared
-- source of truth this classifier is ported from). `strict_btc_orphan` and
-- `weak_btc_orphan` are unaffected.
--
-- Locates the baseline CHECK constraint by its definition text rather than
-- assuming its autogenerated name, so this also tolerates a database whose
-- constraint was already renamed by hand. Idempotent: a re-run after this
-- migration already applied finds no matching old-spelling rows or
-- old-spelling constraint and is a no-op.

DO $$
DECLARE
    old_check_name TEXT;
BEGIN
    -- Drop the old-spelling CHECK before rewriting rows: the baseline
    -- constraint does not allow 'excluded', so updating a row under it would
    -- abort the migration on any database holding a 'btc_stale_excluded' row.
    -- The whole DO block is one transaction, so no row is ever left
    -- unconstrained on failure.
    SELECT conname INTO old_check_name
    FROM pg_constraint
    WHERE conrelid = 'block'::regclass
      AND contype = 'c'
      AND pg_get_constraintdef(oid) LIKE '%btc_stale_excluded%';

    IF old_check_name IS NOT NULL THEN
        EXECUTE format('ALTER TABLE block DROP CONSTRAINT %I', old_check_name);
    END IF;

    UPDATE block SET btc_orphan_class = 'excluded' WHERE btc_orphan_class = 'btc_stale_excluded';

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'block'::regclass AND conname = 'block_btc_orphan_class_check'
    ) THEN
        ALTER TABLE block ADD CONSTRAINT block_btc_orphan_class_check CHECK (
            btc_orphan_class IS NULL
            OR btc_orphan_class IN ('strict_btc_orphan', 'weak_btc_orphan', 'excluded')
        );
    END IF;
END;
$$;

COMMENT ON COLUMN block.btc_orphan_class IS
  'Derived refinement of kind=''unknown'': strict_btc_orphan / weak_btc_orphan / excluded, set by the reconciler only for Core-attested-absent BTC-PoW-valid parents. NULL = pending (not yet Core-checked, or beyond the committed nBits table horizon). Always NULL for canonical/stale.';
