//! Deterministic generation of the registry-derived artifacts.
//!
//! These are PURE functions (no IO): they render the source-seed migration SQL
//! and the frontend chain-metadata ES module from [`SOURCE_REGISTRY`]. The
//! `gen-source-artifacts` binary is a thin IO shell around them, and a test
//! asserts the committed files equal this output (the drift gate).
//!
//! Output is deterministic: dict keys are sorted, formatting is fixed, and all
//! string values go through `serde_json` so escaping is correct.

use std::collections::{BTreeMap, BTreeSet};

use serde::{Deserialize, Serialize};
use serde_json::{Map, Value, json};

use super::SOURCE_REGISTRY;

/// Path of the generated seed migration, relative to the repo root.
pub const SEED_SQL_PATH: &str = "migrations/0002_seed_sources.sql";
/// Path of the generated frontend metadata module, relative to the repo root.
pub const FRONTEND_JS_PATH: &str = "www/js/source-registry.generated.js";

/// Hand-authored, slug-keyed per-chain editorial profiles (history + technical +
/// provenance) surfaced in the frontend source modal. Embedded at compile time so
/// `render_frontend_js` stays a pure function (no runtime I/O), mirroring the rest
/// of this module. Edit `data/sources/chain_profiles.json`, then run
/// `just gen-source-artifacts`.
const CHAIN_PROFILES_JSON: &str = include_str!("../../../../data/sources/chain_profiles.json");

/// The DO-NOT-EDIT banner prepended to both generated artifacts. Each line is
/// re-prefixed with the target comment syntax (`-- ` for SQL, `// ` for JS), so
/// the body itself carries no comment markers.
const GENERATED_BANNER: &str = "GENERATED by `just gen-source-artifacts` from src/source_registry (Rust).\nDO NOT EDIT BY HAND. Drift from the registry fails CI.";

/// Escape a string for a single-quoted PostgreSQL string literal.
fn sql_str(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

/// Render `migrations/0002_seed_sources.sql`: the registry-driven baseline source
/// seed. Begins with a fail-fast guard so it can only run against a freshly reset
/// (empty `source`) database, never in-place on a populated one.
pub fn render_seed_sql() -> String {
    let mut out = String::new();
    out.push_str("-- 0002_seed_sources.sql\n");
    for line in GENERATED_BANNER.lines() {
        out.push_str("-- ");
        out.push_str(line);
        out.push('\n');
    }
    out.push_str(
        "--\n\
         -- Seeds every `source` row from the Source Lifecycle Registry in registry\n\
         -- order, so `source.id` (GENERATED ALWAYS AS IDENTITY) is assigned 1..N in\n\
         -- that order. This is a registry-generated BASELINE seed that replaces the\n\
         -- previously scattered per-source seed migrations; it requires a fresh /\n\
         -- reset database. See migrations/README.md (source-registry baseline reset).\n\
         --\n\
         -- The fail-fast guard below raises if `source` is already populated, so an\n\
         -- accidental in-place run on an un-reset database aborts cleanly (the\n\
         -- migrate-safe backup stays intact) instead of appending rows with wrong ids.\n\n",
    );

    out.push_str("DO $$\nBEGIN\n    IF EXISTS (SELECT 1 FROM source) THEN\n");
    out.push_str(
        "        RAISE EXCEPTION 'source table is not empty: 0002_seed_sources is a registry-generated baseline seed that requires a fresh / reset database (see migrations/README.md, source-registry baseline reset).';\n",
    );
    out.push_str("    END IF;\nEND;\n$$;\n\n");

    // Reset the identity sequence so ids are exactly 1..N even if `source` is
    // empty but the sequence had advanced (rows inserted then deleted in a
    // non-reset database); `source.id` order is a registry contract.
    out.push_str("ALTER TABLE source ALTER COLUMN id RESTART WITH 1;\n\n");

    out.push_str("INSERT INTO source (code, kind, chain, instance, created_at)\nVALUES\n");
    let last = SOURCE_REGISTRY.len() - 1;
    for (idx, s) in SOURCE_REGISTRY.iter().enumerate() {
        let instance = match s.instance {
            Some(inst) => sql_str(inst),
            None => "NULL".to_owned(),
        };
        out.push_str("    (");
        out.push_str(&sql_str(s.code));
        out.push_str(", ");
        out.push_str(&sql_str(s.kind.as_str()));
        out.push_str(", ");
        out.push_str(&sql_str(s.chain));
        out.push_str(", ");
        out.push_str(&instance);
        out.push_str(", extract(epoch from now())::bigint)");
        out.push_str(if idx == last { ";\n" } else { ",\n" });
    }
    out
}

/// Real-world status of a chain TODAY, independent of how this monitor ingests
/// it (a `historical` dataset chain can still be `active`). Validated by
/// deserialization: an out-of-set value fails generation. The declaration order
/// is not semantic; frontend output serializes the lowercase labels only.
#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
enum ChainStatus {
    Active,
    Zombie,
    Dormant,
    Dead,
}

/// One per-chain editorial profile, keyed by chain slug in `chain_profiles.json`.
/// `deny_unknown_fields` catches typo'd keys; required `String` fields are
/// non-empty-checked in [`load_chain_profiles`]. Field declaration order is the
/// emitted JSON order (kept deterministic for the drift gate).
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ChainProfile {
    ticker: String,
    chain_status: ChainStatus,
    status_detail: String,
    tagline: String,
    /// The source-rail kicker for every source: a `year · cadence` summary for
    /// live/parent chains (e.g. `2011 · ~10 min blocks`) or a Bitcoin
    /// merge-mining operating window for historical chains (e.g. `2018-2019`).
    /// Required for every registry chain (enforced in [`load_chain_profiles`]).
    byline: String,
    /// Live/parent sources only: the modal Stats-tab "Data Used" / "Miner
    /// Attribution" copy. `None` for historical chains, whose Stats tab omits
    /// those rows (their capture/provenance lives in the Technical tab).
    #[serde(skip_serializing_if = "Option::is_none", default)]
    help: Option<ProfileHelp>,
    /// Frontend display config feeding the `CHAIN_DISPLAY_NAMES` / `CHAIN_COLORS`
    /// / `SOURCE_DISPLAY_ORDER` dicts. Each field is optional; the frontend keeps
    /// its title-case / hash-color / default-order fallbacks for absent values.
    /// `skip_serializing` keeps it out of `CHAIN_PROFILES` (it drives the small
    /// keyed dicts instead).
    #[serde(skip_serializing, default)]
    display: Option<ProfileDisplay>,
    history: ProfileHistory,
    technical: ProfileTechnical,
    provenance: ProfileProvenance,
    /// Verifiable external sources for this chain's claims. Prose fields embed
    /// `[^N]` markers that reference these by `id`; the modal renders them as
    /// superscript links plus a per-tab "Sources" list. Validated in
    /// [`load_chain_profiles`]: ids unique + every marker resolves + no orphans.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    references: Vec<Reference>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ProfileHelp {
    data: String,
    pool: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ProfileDisplay {
    #[serde(skip_serializing_if = "Option::is_none", default)]
    name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    color: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    order: Option<u8>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ProfileHistory {
    founded: String,
    merge_mining: String,
    ended: String,
    narrative: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ProfileTechnical {
    mechanism: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    uniqueness: Option<String>,
    capture: String,
    bitcoin_relevance: String,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    notable: Vec<String>,
    /// Scannable "At a glance" identifiers (chain ID, activation height, RPC),
    /// rendered as a kv at the top of the Technical tab. Values may carry `code`
    /// spans and `[^N]` citation markers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    key_facts: Vec<KeyFact>,
    /// Recovery-outcome bullets (validated stale counts, recovered windows,
    /// novelty vs upstream) rendered in the Capture tab's Recovery section, NOT
    /// in Technical. May carry `code` spans and `[^N]` citation markers.
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    recovery: Vec<String>,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct ProfileProvenance {
    source: String,
    coverage: String,
}

/// One external source backing a chain's claims, cited from prose via `[^id]`.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct Reference {
    id: u32,
    label: String,
    url: String,
}

/// One "At a glance" identifier row in the Technical tab.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct KeyFact {
    label: String,
    value: String,
}

/// Extract the ids from `[^N]` citation markers in `text` (N = ASCII digits).
/// Keeps prose markers and the `references` list in sync in [`load_chain_profiles`].
fn citation_ids(text: &str) -> Vec<u32> {
    let bytes = text.as_bytes();
    let mut ids = Vec::new();
    let mut i = 0;
    while i + 2 < bytes.len() {
        if bytes[i] == b'[' && bytes[i + 1] == b'^' && bytes[i + 2].is_ascii_digit() {
            let mut j = i + 2;
            while j < bytes.len() && bytes[j].is_ascii_digit() {
                j += 1;
            }
            if j < bytes.len()
                && bytes[j] == b']'
                && let Ok(id) = text[i + 2..j].parse::<u32>()
            {
                ids.push(id);
            }
            i = j;
        } else {
            i += 1;
        }
    }
    ids
}

/// Parse + validate the embedded `chain_profiles.json` into a slug-sorted map.
/// Panics (caught by tests + surfaced by the gen binary) on: a parse/enum error,
/// a profile for a chain not in [`SOURCE_REGISTRY`], a registry chain missing a
/// profile, or any required string being empty. This is the single chokepoint
/// that keeps the frontend's `CHAIN_PROFILES` complete and registry-consistent.
fn load_chain_profiles() -> BTreeMap<String, ChainProfile> {
    let profiles: BTreeMap<String, ChainProfile> = serde_json::from_str(CHAIN_PROFILES_JSON)
        .expect("chain_profiles.json parses into a {chain: ChainProfile} map");

    let registry_chains: BTreeSet<&str> = SOURCE_REGISTRY.iter().map(|s| s.chain).collect();
    for chain in profiles.keys() {
        assert!(
            registry_chains.contains(chain.as_str()),
            "chain_profiles.json: profile for unknown chain {chain:?} (not in SOURCE_REGISTRY)"
        );
    }
    for chain in &registry_chains {
        assert!(
            profiles.contains_key(*chain),
            "chain_profiles.json: missing profile for registry chain {chain:?}"
        );
    }
    for (chain, p) in &profiles {
        let nonempty = |label: &str, value: &str| {
            assert!(
                !value.trim().is_empty(),
                "chain_profiles.json [{chain}]: empty {label}"
            );
        };
        nonempty("ticker", &p.ticker);
        nonempty("status_detail", &p.status_detail);
        nonempty("tagline", &p.tagline);
        nonempty("byline", &p.byline);
        nonempty("history.founded", &p.history.founded);
        nonempty("history.merge_mining", &p.history.merge_mining);
        nonempty("history.ended", &p.history.ended);
        nonempty("history.narrative", &p.history.narrative);
        nonempty("technical.mechanism", &p.technical.mechanism);
        nonempty("technical.capture", &p.technical.capture);
        nonempty(
            "technical.bitcoin_relevance",
            &p.technical.bitcoin_relevance,
        );
        nonempty("provenance.source", &p.provenance.source);
        nonempty("provenance.coverage", &p.provenance.coverage);
        if let Some(uniqueness) = &p.technical.uniqueness {
            nonempty("technical.uniqueness", uniqueness);
        }
        if let Some(help) = &p.help {
            nonempty("help.data", &help.data);
            nonempty("help.pool", &help.pool);
        }
        if let Some(display) = &p.display {
            if let Some(name) = &display.name {
                nonempty("display.name", name);
            }
            if let Some(color) = &display.color {
                nonempty("display.color", color);
            }
        }
        for note in &p.technical.notable {
            nonempty("technical.notable[]", note);
        }
        for item in &p.technical.recovery {
            nonempty("technical.recovery[]", item);
        }
        validate_chain_citations(chain, p);
    }
    profiles
}

/// Validate a chain's `key_facts` and `references`: non-empty fields, unique
/// reference ids, http urls, and that every `[^N]` prose marker resolves to a
/// declared reference that is itself cited at least once. (Escaping the rendered
/// url/label is the frontend's job, not the `starts_with("http")` check here.)
fn validate_chain_citations(chain: &str, p: &ChainProfile) {
    for kf in &p.technical.key_facts {
        assert!(
            !kf.label.trim().is_empty(),
            "chain_profiles.json [{chain}]: empty technical.key_facts[].label"
        );
        assert!(
            !kf.value.trim().is_empty(),
            "chain_profiles.json [{chain}]: empty technical.key_facts[].value"
        );
    }
    let mut ref_ids: BTreeSet<u32> = BTreeSet::new();
    for r in &p.references {
        assert!(
            r.id > 0,
            "chain_profiles.json [{chain}]: reference id must be > 0"
        );
        assert!(
            ref_ids.insert(r.id),
            "chain_profiles.json [{chain}]: duplicate reference id {}",
            r.id
        );
        assert!(
            !r.label.trim().is_empty(),
            "chain_profiles.json [{chain}]: empty references[].label"
        );
        assert!(
            r.url.starts_with("http"),
            "chain_profiles.json [{chain}]: reference {} url must start with http",
            r.id
        );
    }
    let mut scan: Vec<&str> = vec![
        &p.status_detail,
        &p.history.founded,
        &p.history.merge_mining,
        &p.history.ended,
        &p.history.narrative,
        &p.technical.mechanism,
        &p.technical.capture,
        &p.technical.bitcoin_relevance,
        &p.provenance.source,
        &p.provenance.coverage,
    ];
    if let Some(u) = &p.technical.uniqueness {
        scan.push(u);
    }
    scan.extend(p.technical.notable.iter().map(String::as_str));
    scan.extend(p.technical.recovery.iter().map(String::as_str));
    scan.extend(p.technical.key_facts.iter().map(|kf| kf.value.as_str()));
    let mut cited: BTreeSet<u32> = BTreeSet::new();
    for text in &scan {
        for id in citation_ids(text) {
            assert!(
                ref_ids.contains(&id),
                "chain_profiles.json [{chain}]: citation [^{id}] has no matching reference"
            );
            cited.insert(id);
        }
    }
    for r in &p.references {
        assert!(
            cited.contains(&r.id),
            "chain_profiles.json [{chain}]: reference {} is declared but never cited",
            r.id
        );
    }
}

/// Render `www/js/source-registry.generated.js`: the chain-metadata dicts the
/// buildless frontend imports (replacing the hand-maintained dicts in app.js).
/// Only sources with an explicit value contribute to each dict; the frontend
/// keeps its hash-color / title-case / default-order fallbacks for the rest.
pub fn render_frontend_js() -> String {
    // Editorial + display config is sourced from chain_profiles.json (keyed by
    // chain slug); lifecycle is sourced from the Rust registry (keyed by code).
    let profiles = load_chain_profiles();

    let mut colors: BTreeMap<&str, Value> = BTreeMap::new();
    let mut names: BTreeMap<&str, Value> = BTreeMap::new();
    let mut order: BTreeMap<&str, Value> = BTreeMap::new();
    for (chain, p) in &profiles {
        let Some(display) = &p.display else { continue };
        if let Some(color) = &display.color {
            colors.insert(chain.as_str(), json!(color));
        }
        if let Some(name) = &display.name {
            names.insert(chain.as_str(), json!(name));
        }
        if let Some(ord) = display.order {
            order.insert(chain.as_str(), json!(ord));
        }
    }

    let mut lifecycle: BTreeMap<&str, Value> = BTreeMap::new();
    for s in SOURCE_REGISTRY {
        lifecycle.insert(s.code, json!(s.lifecycle.as_str()));
    }

    let mut out = String::new();
    for line in GENERATED_BANNER.lines() {
        out.push_str("// ");
        out.push_str(line);
        out.push('\n');
    }
    out.push('\n');
    out.push_str(&render_js_const("CHAIN_COLORS", &colors));
    out.push_str(&render_js_const("CHAIN_DISPLAY_NAMES", &names));
    out.push_str(&render_js_const("SOURCE_DISPLAY_ORDER", &order));
    out.push_str(&render_js_const("SOURCE_LIFECYCLE", &lifecycle));

    // Slug-keyed editorial profiles (history + technical + provenance) for the
    // source modal. Validated + slug-checked against the registry by
    // `load_chain_profiles`; serialized through serde so escaping is correct and
    // BTreeMap key order is deterministic.
    let profiles_body = serde_json::to_string_pretty(&profiles).expect("chain profiles serialize");
    out.push_str(&format!(
        "export const CHAIN_PROFILES = {profiles_body};\n\n"
    ));
    out
}

/// `export const NAME = <pretty JSON>;\n\n`. JSON object literals are a valid JS
/// subset for these values; pretty-printing a `BTreeMap` is deterministic.
fn render_js_const(name: &str, entries: &BTreeMap<&str, Value>) -> String {
    let map: Map<String, Value> = entries
        .iter()
        .map(|(k, v)| ((*k).to_owned(), v.clone()))
        .collect();
    let body = serde_json::to_string_pretty(&Value::Object(map))
        .expect("registry display values serialize");
    format!("export const {name} = {body};\n\n")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_sql_is_deterministic_and_well_formed() {
        let sql = render_seed_sql();
        assert_eq!(sql, render_seed_sql(), "generation must be deterministic");
        assert!(sql.contains("RAISE EXCEPTION"), "fail-fast guard present");
        assert!(sql.contains("RESTART WITH 1"), "identity reset present");
        assert!(sql.contains("INSERT INTO source"));
        // One VALUES row per registry entry, terminated by a single `;`.
        assert_eq!(sql.matches("    ('").count(), SOURCE_REGISTRY.len());
        // The INSERT is the last statement and ends the file.
        assert!(
            sql.trim_end().ends_with("::bigint);"),
            "ends with the final row"
        );
        // the Bitcoin live source carries its instance; auxpow rows are NULL.
        assert!(sql.contains("'live-chaintip:bitcoin:core', 'live-chaintip', 'bitcoin', 'core'"));
        assert!(sql.contains("'auxpow:namecoin', 'auxpow', 'namecoin', NULL"));
    }

    #[test]
    fn frontend_js_is_deterministic_and_exports_dicts() {
        let js = render_frontend_js();
        assert_eq!(js, render_frontend_js(), "generation must be deterministic");
        for name in [
            "CHAIN_COLORS",
            "CHAIN_DISPLAY_NAMES",
            "SOURCE_DISPLAY_ORDER",
            "SOURCE_LIFECYCLE",
            "CHAIN_PROFILES",
        ] {
            assert!(js.contains(&format!("export const {name} = {{")), "{name}");
        }
        assert!(js.contains("\"namecoin\": \"#8172b2\""));
        // Historical chains now carry an explicit display name (so the frontend
        // renders "CoiledCoin"/"Bitcoin Vault", not a title-cased slug)...
        assert!(js.contains("\"argentum\": \"Argentum\""));
        assert!(js.contains("\"coiledcoin\": \"CoiledCoin\""));
        // ...but still get no explicit color: argentum must be absent from the
        // CHAIN_COLORS block (it falls back to the hashed palette).
        let colors_block = js
            .split("export const CHAIN_COLORS = {")
            .nth(1)
            .and_then(|rest| rest.split("};").next())
            .expect("CHAIN_COLORS block present");
        assert!(
            !colors_block.contains("argentum"),
            "historical chains have no explicit color"
        );
        // Bitcoin has a display name + order but no explicit color (fallback).
        assert!(js.contains("\"bitcoin\": \"Bitcoin\""));
        // Lifecycle is keyed by exact source code so live and historical AuxPoW
        // rows can be separated even though both use kind=auxpow.
        assert!(js.contains("\"auxpow:namecoin\": \"live\""));
        assert!(js.contains("\"auxpow:argentum\": \"historical\""));
        // CHAIN_PROFILES carries the per-chain editorial profile, keyed by slug.
        assert!(js.contains("\"namecoin\": {"));
        assert!(js.contains("\"chain_status\":"));
    }

    #[test]
    fn chain_profiles_cover_every_registry_chain() {
        // load_chain_profiles panics on an unknown profile key, a missing registry
        // chain, an empty required field, or a bad chain_status; calling it here
        // makes the real-corpus completeness contract an explicit, named test.
        let profiles = load_chain_profiles();
        let registry_chains: BTreeSet<&str> = SOURCE_REGISTRY.iter().map(|s| s.chain).collect();
        assert_eq!(
            profiles.len(),
            registry_chains.len(),
            "exactly one profile per distinct registry chain"
        );
        for chain in &registry_chains {
            assert!(profiles.contains_key(*chain), "missing profile for {chain}");
        }
        // The Bitcoin parent chain must also carry a profile (3-tab modal target).
        assert!(profiles.contains_key("bitcoin"));
    }

    #[test]
    fn committed_artifacts_match_registry() {
        // The committed artifacts MUST equal the generator output. This wires the
        // --check drift gate into the standard `cargo test` (the CI tests job runs
        // `cargo test --all-features`), so no separate CI step is required. If this
        // fails, run `just gen-source-artifacts`.
        // CARGO_MANIFEST_DIR is crates/mmm-capture; the committed artifacts
        // live at the repo root two levels up.
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
        let seed = std::fs::read_to_string(format!("{root}/{SEED_SQL_PATH}"))
            .expect("read committed seed SQL");
        assert_eq!(
            seed,
            render_seed_sql(),
            "{SEED_SQL_PATH} drift; run `just gen-source-artifacts`"
        );
        let js = std::fs::read_to_string(format!("{root}/{FRONTEND_JS_PATH}"))
            .expect("read committed frontend JS");
        assert_eq!(
            js,
            render_frontend_js(),
            "{FRONTEND_JS_PATH} drift; run `just gen-source-artifacts`"
        );
    }
}
