//! BTC orphan classification.
//!
//! Refines a Core-attested-absent, BTC-PoW-valid `unknown` parent header into
//! `strict_btc_orphan` / `weak_btc_orphan` / `btc_stale_excluded`, or leaves it
//! pending when the committed nBits table cannot yet give a correct verdict.
//!
//! This is a faithful port of the orphan path of the research classifier
//! (`merge-mining-research/scripts/analysis/classify_btc_stale_relevance.py`:
//! `classify_source_row` + `strict_height_evidence`/`resolve_height` +
//! `EpochTimeLookup`), with ONE documented monitor divergence: where the
//! research excludes/weaks a row whose height or time is beyond its per-run
//! cache, the monitor leaves it [`BtcOrphanVerdict::Pending`] because the
//! embedded table is a committed artifact that lags the BTC tip and is
//! regenerated by `scripts/gen-nbits-table.py`.
//!
//! The Bitcoin Core non-membership gate (the header must be provably absent from
//! Core's chain) lives in the read-model reconciler, not here; this module only
//! decides the nBits-evidence verdict for rows that already passed that gate.

use bitcoin::CompactTarget;

use crate::nbits_table::{NbitsLookup, NbitsTable, NbitsVerdict, WeakVerdict, table};

/// BIP34 activation height. A decoded coinbase "height" below this is not
/// reliable strict evidence (pre-BIP34 coinbases can look height-like).
pub const BIP34_HEIGHT: i32 = 227_931;

/// Source chains whose producers embed a REAL Bitcoin parent coinbase scriptSig
/// (the Namecoin-family raw-AuxPoW form), so a decoded BIP34 height is usable as
/// strict orphan evidence. Ported from the research `BTC_COINBASE_SCRIPTSIG_CHAINS`
/// allowlist, with `fractal-bitcoin` mapped to this repo's `fractal` source
/// chain. RSK (NULL coinbase), Hathor (reconstructed coinbase), and Xaya are
/// deliberately absent: they are weak-only.
pub const STRICT_BIP34_CHAINS: &[&str] = &[
    "argentum",
    "bitcoin-vault",
    "bitmark",
    "coiledcoin",
    "crown",
    "devcoin",
    "elastos",
    "emercoin",
    "fractal",
    "geistgeld",
    "groupcoin",
    "huntercoin",
    "i0coin",
    "ixcoin",
    "myriadcoin",
    "namecoin",
    "syscoin",
    "terracoin",
    "unobtanium",
];

/// Whether `chain` (a `source.chain` value) may contribute strict BIP34-height
/// orphan evidence.
pub fn is_strict_bip34_chain(chain: &str) -> bool {
    STRICT_BIP34_CHAINS.contains(&chain)
}

/// Derived BTC orphan classification for a Core-attested-absent, BTC-PoW-valid
/// `unknown` parent.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BtcOrphanVerdict {
    /// Strong: BIP34 height evidence plus matching BTC nBits at that height.
    Strict,
    /// Plausible: no strict height, but timestamp-selected BTC nBits matches
    /// within +/-1 retarget epoch.
    Weak,
    /// PoW-valid but not a BTC orphan (non-BTC scratch substrate, or
    /// insufficient evidence under the available table).
    Excluded,
    /// The committed nBits table cannot yet give a correct verdict (height or
    /// time beyond its upper horizon). Leave `block.btc_orphan_class` NULL and
    /// revisit after a table regen + `reclassify-unknown-parents --recheck-orphans`.
    Pending,
}

impl BtcOrphanVerdict {
    /// `block.btc_orphan_class` DB value; `None` (SQL NULL) for `Pending`.
    pub fn as_db_str(self) -> Option<&'static str> {
        match self {
            Self::Strict => Some("strict_btc_orphan"),
            Self::Weak => Some("weak_btc_orphan"),
            Self::Excluded => Some("btc_stale_excluded"),
            Self::Pending => None,
        }
    }
}

/// Classify against the embedded table. `strict_height` is the parent's BIP34
/// coinbase height when the parent is from a strict-eligible chain (see
/// [`is_strict_bip34_chain`]); pass `None` for weak-only chains. The returned
/// `&str` is a diagnostic reason code.
pub fn classify_btc_orphan(
    header_time: i64,
    header_bits: CompactTarget,
    strict_height: Option<i32>,
) -> (BtcOrphanVerdict, &'static str) {
    classify_btc_orphan_with(table(), header_time, header_bits, strict_height)
}

/// Table-injected core (testable with a synthetic [`NbitsTable`]). Evaluates the
/// verdict precedence top-down; first match wins.
pub fn classify_btc_orphan_with(
    nbits: &NbitsTable,
    header_time: i64,
    header_bits: CompactTarget,
    strict_height: Option<i32>,
) -> (BtcOrphanVerdict, &'static str) {
    // Belt-and-suspenders BIP34 activation floor: a height below activation is
    // never usable strict evidence even if a caller passed one.
    let strict_height = strict_height.filter(|&height| height >= BIP34_HEIGHT);

    // (a) Upper-horizon PENDING precedence (the documented monitor divergence).
    // Checked BEFORE the strict time-epoch fallback and the weak path so an
    // above-table row is never bypassed into Excluded by the timestamp path.
    if let Some(height) = strict_height
        && matches!(nbits.expected_nbits(height), NbitsLookup::AboveTable)
    {
        return (BtcOrphanVerdict::Pending, "above_nbits_height_horizon");
    }
    if let Some(covered_max_time) = nbits.covered_max_time()
        && header_time > covered_max_time
    {
        return (BtcOrphanVerdict::Pending, "above_nbits_time_horizon");
    }

    // (b) STRICT (in-horizon, strict-eligible, time-epoch-consistent).
    if let Some(height) = strict_height {
        let time_epoch_consistent = if nbits.has_time_table() {
            match nbits.epoch_height_for_time(header_time) {
                Some(time_epoch) => {
                    (time_epoch..time_epoch + nbits.epoch_interval()).contains(&height)
                }
                // Timestamp before the earliest covered epoch: disable strict,
                // fall through to weak.
                None => false,
            }
        } else {
            // No time table: the anti-fabrication time-epoch guard is skipped and
            // strict resolves by height + nBits alone. This matches the research
            // `resolve_height`, which skips the guard when `epoch_headers` is
            // empty, and lets strict orphans be detected from the committed
            // height->nBits table before the time table is regenerated.
            true
        };
        if time_epoch_consistent {
            match nbits.classify_nbits(Some(height), header_bits) {
                NbitsVerdict::Valid => {
                    return (BtcOrphanVerdict::Strict, "strict_height_nbits_match");
                }
                NbitsVerdict::Contaminant => {
                    return (BtcOrphanVerdict::Excluded, "non_btc_epoch_bits");
                }
                // Height below the table minimum: fall through to weak.
                NbitsVerdict::Indeterminate => {}
                // Handled by (a); kept for exhaustiveness.
                NbitsVerdict::AboveTableHorizon => {
                    return (BtcOrphanVerdict::Pending, "above_nbits_height_horizon");
                }
            }
        }
    }

    // (c) WEAK (in-horizon).
    match nbits.classify_nbits_by_time(header_time, header_bits) {
        WeakVerdict::Match => (BtcOrphanVerdict::Weak, "timestamp_epoch_nbits_match"),
        WeakVerdict::NonBtcEpochBits => (BtcOrphanVerdict::Excluded, "non_btc_epoch_bits"),
        WeakVerdict::BelowFloor => (BtcOrphanVerdict::Excluded, "insufficient_evidence"),
        WeakVerdict::NoTimeTable => (BtcOrphanVerdict::Excluded, "insufficient_epoch_cache"),
        // Handled by (a); kept for exhaustiveness.
        WeakVerdict::AboveHorizon => (BtcOrphanVerdict::Pending, "above_nbits_time_horizon"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const AAAA: &str = "1d00aaaa";
    const BBBB: &str = "1d00bbbb";
    const CCCC: &str = "1d00cccc";
    const DDDD: &str = "1d00dddd";

    fn bits(hex: &str) -> CompactTarget {
        CompactTarget::from_consensus(u32::from_str_radix(hex, 16).unwrap())
    }

    /// Four contiguous epochs around a strict-eligible height, each with a
    /// distinct nBits, plus per-epoch times and a tip time bound above the last
    /// epoch. Epoch interval 2016; epoch starts are real BIP34-era heights.
    ///   height 294336 time 1000 bits AAAA
    ///   height 296352 time 2000 bits BBBB
    ///   height 298368 time 3000 bits CCCC
    ///   height 300384 time 4000 bits DDDD   (last covered epoch)
    ///   covered_max_time 5000                (partial latest epoch upper bound)
    fn std_table() -> NbitsTable {
        NbitsTable::from_test_parts(
            2016,
            0,
            300_384,
            Some(5000),
            &[
                (294_336, u32::from_str_radix(AAAA, 16).unwrap()),
                (296_352, u32::from_str_radix(BBBB, 16).unwrap()),
                (298_368, u32::from_str_radix(CCCC, 16).unwrap()),
                (300_384, u32::from_str_radix(DDDD, 16).unwrap()),
            ],
            &[
                (294_336, 1000),
                (296_352, 2000),
                (298_368, 3000),
                (300_384, 4000),
            ],
        )
    }

    fn classify(table: &NbitsTable, time: i64, hex: &str, height: Option<i32>) -> BtcOrphanVerdict {
        classify_btc_orphan_with(table, time, bits(hex), height).0
    }

    #[test]
    fn strict_height_nbits_match_is_strict() {
        // height 297000 lives in epoch 296352 (BBBB); timestamp 2500 selects the
        // same epoch, so the time-epoch guard passes and nBits match.
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 2500, bits(BBBB), Some(297_000));
        assert_eq!(verdict, BtcOrphanVerdict::Strict);
        assert_eq!(reason, "strict_height_nbits_match");
    }

    #[test]
    fn strict_height_nbits_mismatch_is_excluded() {
        // Same epoch, but the header carries a different (non-BTC) nBits.
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 2500, bits(DDDD), Some(297_000));
        assert_eq!(verdict, BtcOrphanVerdict::Excluded);
        assert_eq!(reason, "non_btc_epoch_bits");
    }

    #[test]
    fn strict_height_time_epoch_mismatch_falls_back_to_weak() {
        // height 297000 (epoch 296352) but timestamp 3500 selects epoch 298368;
        // strict is disabled and the weak path matches BBBB as the -1 neighbor of
        // CCCC's epoch... use CCCC so it matches the timestamp-selected epoch.
        let t = std_table();
        let (verdict, _) = classify_btc_orphan_with(&t, 3500, bits(CCCC), Some(297_000));
        assert_eq!(verdict, BtcOrphanVerdict::Weak);
    }

    #[test]
    fn strict_height_above_table_horizon_is_pending_even_when_time_out_of_range() {
        // Height epoch beyond covered_max_height AND time beyond covered_max_time:
        // the height-horizon pending check fires first.
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 9000, bits(BBBB), Some(900_000));
        assert_eq!(verdict, BtcOrphanVerdict::Pending);
        assert_eq!(reason, "above_nbits_height_horizon");
    }

    #[test]
    fn time_above_horizon_is_pending_for_weak_only_row() {
        // Weak-only (no strict height); timestamp beyond covered_max_time -> the
        // table is stale for this row, so pending, not excluded.
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 9000, bits(BBBB), None);
        assert_eq!(verdict, BtcOrphanVerdict::Pending);
        assert_eq!(reason, "above_nbits_time_horizon");
    }

    #[test]
    fn weak_only_timestamp_epoch_match_is_weak() {
        // RSK-style: no strict height. Timestamp 2500 -> epoch 296352; BBBB is the
        // exact-epoch nBits.
        let t = std_table();
        assert_eq!(classify(&t, 2500, BBBB, None), BtcOrphanVerdict::Weak);
    }

    #[test]
    fn weak_accepts_plus_minus_one_neighbor() {
        // Timestamp 2500 -> epoch 296352. Allowed set is {AAAA(-1), BBBB(0), CCCC(+1)}.
        let t = std_table();
        assert_eq!(classify(&t, 2500, AAAA, None), BtcOrphanVerdict::Weak);
        assert_eq!(classify(&t, 2500, CCCC, None), BtcOrphanVerdict::Weak);
    }

    #[test]
    fn weak_rejects_two_epochs_away() {
        // Timestamp 2500 -> epoch 296352; DDDD is +2 epochs away.
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 2500, bits(DDDD), None);
        assert_eq!(verdict, BtcOrphanVerdict::Excluded);
        assert_eq!(reason, "non_btc_epoch_bits");
    }

    #[test]
    fn weak_sparse_neighbor_is_not_treated_as_pm1() {
        // Table missing the 294336 epoch: for epoch 296352 the allowed set is only
        // {BBBB, CCCC}; AAAA must NOT be accepted as a phantom -1 neighbor.
        let t = NbitsTable::from_test_parts(
            2016,
            0,
            300_384,
            Some(5000),
            &[
                (296_352, u32::from_str_radix(BBBB, 16).unwrap()),
                (298_368, u32::from_str_radix(CCCC, 16).unwrap()),
                (300_384, u32::from_str_radix(DDDD, 16).unwrap()),
            ],
            &[(296_352, 2000), (298_368, 3000), (300_384, 4000)],
        );
        let (verdict, reason) = classify_btc_orphan_with(&t, 2500, bits(AAAA), None);
        assert_eq!(verdict, BtcOrphanVerdict::Excluded);
        assert_eq!(reason, "non_btc_epoch_bits");
    }

    #[test]
    fn weak_below_time_floor_is_excluded_insufficient_evidence() {
        // Timestamp below the earliest epoch time (1000).
        let t = std_table();
        let (verdict, reason) = classify_btc_orphan_with(&t, 500, bits(BBBB), None);
        assert_eq!(verdict, BtcOrphanVerdict::Excluded);
        assert_eq!(reason, "insufficient_evidence");
    }

    #[test]
    fn no_time_table_is_excluded_insufficient_epoch_cache() {
        // covered_max_time None / empty time map -> weak inert; a weak-only row is
        // excluded as insufficient, never silently misclassified.
        let t = NbitsTable::from_test_parts(
            2016,
            0,
            300_384,
            None,
            &[(296_352, u32::from_str_radix(BBBB, 16).unwrap())],
            &[],
        );
        let (verdict, reason) = classify_btc_orphan_with(&t, 2500, bits(BBBB), None);
        assert_eq!(verdict, BtcOrphanVerdict::Excluded);
        assert_eq!(reason, "insufficient_epoch_cache");
    }

    #[test]
    fn strict_resolves_without_a_time_table() {
        // Committed-table state: height->nBits present, but no time table. The
        // time-epoch guard is skipped, so a strict-eligible row still resolves by
        // height + nBits alone (weak, by contrast, stays inert).
        let t = NbitsTable::from_test_parts(
            2016,
            0,
            300_384,
            None,
            &[(296_352, u32::from_str_radix(BBBB, 16).unwrap())],
            &[],
        );
        let (verdict, reason) = classify_btc_orphan_with(&t, 1_000_000, bits(BBBB), Some(297_000));
        assert_eq!(verdict, BtcOrphanVerdict::Strict);
        assert_eq!(reason, "strict_height_nbits_match");
    }

    #[test]
    fn pre_bip34_strict_height_is_ignored_and_falls_to_weak() {
        // A decoded height below BIP34 activation is not strict evidence; the row
        // is classified by the weak path instead (here BBBB matches its epoch).
        let t = std_table();
        let (verdict, _) = classify_btc_orphan_with(&t, 2500, bits(BBBB), Some(100_000));
        assert_eq!(verdict, BtcOrphanVerdict::Weak);
    }

    #[test]
    fn strict_chain_allowlist_excludes_weak_only_chains() {
        assert!(is_strict_bip34_chain("namecoin"));
        assert!(is_strict_bip34_chain("syscoin"));
        assert!(is_strict_bip34_chain("fractal"));
        assert!(!is_strict_bip34_chain("rsk"));
        assert!(!is_strict_bip34_chain("hathor"));
        assert!(!is_strict_bip34_chain("xaya"));
    }

    #[test]
    fn verdict_db_strings() {
        assert_eq!(
            BtcOrphanVerdict::Strict.as_db_str(),
            Some("strict_btc_orphan")
        );
        assert_eq!(BtcOrphanVerdict::Weak.as_db_str(), Some("weak_btc_orphan"));
        assert_eq!(
            BtcOrphanVerdict::Excluded.as_db_str(),
            Some("btc_stale_excluded")
        );
        assert_eq!(BtcOrphanVerdict::Pending.as_db_str(), None);
    }
}
