//! Findings registry: the curated evidence-backed editorial corpus behind the
//! frontend Findings view.
//!
//! One JSON file per finding lives in `data/findings/` (filename `<slug>.json`).
//! Unlike `chain_profiles.json` (one file keyed by the closed registry chain
//! set), findings are an open-ended, append-mostly corpus, so per-file
//! authoring keeps each finding independently reviewable. [`load_findings`]
//! reads a directory, validates every finding (schema shape via serde,
//! content invariants + citation integrity here), and returns the corpus
//! sorted newest-first. [`render_findings_js`] is a pure renderer emitting the
//! committed `www/js/findings.generated.js`; the `gen-source-artifacts` binary
//! is the IO shell and a test asserts the committed file equals this output
//! (the drift gate, mirroring `source_registry::generate`).

use std::collections::BTreeSet;
use std::path::Path;

use serde::{Deserialize, Serialize};
use time::Date;

use crate::source_registry::SOURCE_REGISTRY;
use crate::source_registry::generate::citation_ids;

/// Path of the generated findings module, relative to the repo root.
pub const FINDINGS_JS_PATH: &str = "www/js/findings.generated.js";
/// Directory of the hand-authored per-finding JSON files, repo-root relative.
pub const FINDINGS_DATA_DIR: &str = "data/findings";

/// The DO-NOT-EDIT banner prepended to the generated findings module. Each
/// line is re-prefixed with `// `; the body carries no comment markers. Names
/// this module and `data/findings/` (not the source registry) as provenance.
const GENERATED_BANNER: &str = "GENERATED by `just gen-source-artifacts` from data/findings/ (src/findings_registry.rs).\nDO NOT EDIT BY HAND. Drift from the findings data fails CI.";

/// Editorial category of a finding; drives the feed's category chip and
/// filter. Serialized kebab-case; an out-of-set value fails generation.
#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum Category {
    HashrateShift,
    PoolExit,
    ChainIncident,
    DatasetNote,
}

/// Whether the underlying situation is still developing. Serialized lowercase.
#[derive(Debug, Clone, Copy, Deserialize, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Status {
    Ongoing,
    Monitoring,
    Concluded,
}

/// Typed evidence anchor kinds. `btc-height` deep-links into the tree view,
/// `source` opens the source dialog; `child-height` and `pool` render as
/// informational chips.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum AnchorKind {
    BtcHeight,
    ChildHeight,
    Source,
    Pool,
}

/// One typed evidence anchor. `value` is a string for every kind; height
/// kinds must parse as positive integers (validated below).
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Anchor {
    kind: AnchorKind,
    value: String,
    #[serde(skip_serializing_if = "Option::is_none", default)]
    label: Option<String>,
}

/// One external source backing a finding's claims, cited from prose via
/// `[^id]`. Same semantics as the chain-profile references: unique positive
/// ids, http(s) urls, and every declared reference cited at least once.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Reference {
    id: u32,
    label: String,
    url: String,
}

/// Figure kinds the frontend renderer supports. `line-series` is a single
/// time series with optional event markers (the collapse/exit/halt shapes the
/// evidence keeps producing). Bitmap `image` figures are deliberately absent:
/// structured data stays theme-aware and validated; add an image kind only
/// when a finding needs an irreducible graphic.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum FigureKind {
    LineSeries,
}

/// One time-series sample. `t` is an ISO `YYYY-MM-DD` date or
/// `YYYY-MM-DDTHH:MM` UTC datetime; `v` is the plotted value.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FigurePoint {
    t: String,
    v: f64,
}

/// One labeled vertical event marker inside a figure's time range.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct FigureMarker {
    t: String,
    label: String,
}

/// One structured evidence figure, rendered client-side from data (never a
/// committed bitmap) so it stays theme-aware and drift-gated with the rest of
/// the corpus.
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Figure {
    kind: FigureKind,
    caption: String,
    /// Axis label for the plotted value (e.g. `block weight (log2 difficulty)`).
    y_label: String,
    points: Vec<FigurePoint>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    markers: Vec<FigureMarker>,
    /// Data-provenance note shown under the caption.
    note: String,
}

/// One curated finding. Field declaration order is the emitted JSON order
/// (kept deterministic for the drift gate). `deny_unknown_fields` catches
/// typo'd keys; content invariants live in [`validate_finding`].
#[derive(Debug, Clone, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct Finding {
    slug: String,
    title: String,
    category: Category,
    status: Status,
    /// Date the observed change began (ISO `YYYY-MM-DD`).
    observed_at: String,
    /// Optional end of the observation window; must not precede `observed_at`.
    #[serde(skip_serializing_if = "Option::is_none", default)]
    observed_until: Option<String>,
    published_at: String,
    /// Registered source codes this finding explains; drives the shared
    /// Source-filter matching and the slice-3 "why?" cross-links.
    affected_sources: Vec<String>,
    summary: String,
    /// Article prose; paragraphs split on `\n\n` (the `history.narrative`
    /// convention) and may carry `code` spans and `[^N]` citation markers.
    body: String,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    anchors: Vec<Anchor>,
    #[serde(skip_serializing_if = "Vec::is_empty", default)]
    figures: Vec<Figure>,
    references: Vec<Reference>,
}

/// Parse an ISO `YYYY-MM-DD` string as a real calendar date (a format match
/// with an impossible date, e.g. `2026-02-30`, is rejected).
fn parse_date(value: &str) -> Result<Date, String> {
    let format =
        time::format_description::parse("[year]-[month]-[day]").expect("static date format parses");
    Date::parse(value, &format).map_err(|err| format!("invalid calendar date {value:?}: {err}"))
}

/// Parse a figure instant: an ISO `YYYY-MM-DD` date (midnight) or a
/// `YYYY-MM-DDTHH:MM` UTC datetime, as a comparable `PrimitiveDateTime`.
fn parse_instant(value: &str) -> Result<time::PrimitiveDateTime, String> {
    if let Ok(date) = parse_date(value) {
        return Ok(date.midnight());
    }
    let format = time::format_description::parse("[year]-[month]-[day]T[hour]:[minute]")
        .expect("static datetime format parses");
    time::PrimitiveDateTime::parse(value, &format).map_err(|err| {
        format!("invalid instant {value:?} (want YYYY-MM-DD or YYYY-MM-DDTHH:MM): {err}")
    })
}

/// Validate one figure: non-empty caption/axis/note, at least two finite
/// points in strictly increasing time order, and markers that land inside the
/// plotted range.
fn validate_figure(ctx: &impl Fn(String) -> String, figure: &Figure) -> Result<(), String> {
    for (label, value) in [
        ("figure caption", &figure.caption),
        ("figure y_label", &figure.y_label),
        ("figure note", &figure.note),
    ] {
        if value.trim().is_empty() {
            return Err(ctx(format!("empty {label}")));
        }
    }
    if figure.points.len() < 2 {
        return Err(ctx("figure needs at least two points".into()));
    }
    let mut instants = Vec::with_capacity(figure.points.len());
    for point in &figure.points {
        if !point.v.is_finite() {
            return Err(ctx(format!(
                "figure point {:?} has a non-finite value",
                point.t
            )));
        }
        instants.push(parse_instant(&point.t).map_err(|e| ctx(format!("figure point: {e}")))?);
    }
    if instants.windows(2).any(|pair| pair[0] >= pair[1]) {
        return Err(ctx(
            "figure points must be strictly increasing in time".into()
        ));
    }
    let (first, last) = (instants[0], *instants.last().expect("two or more points"));
    for marker in &figure.markers {
        if marker.label.trim().is_empty() {
            return Err(ctx(format!(
                "figure marker {:?} has an empty label",
                marker.t
            )));
        }
        let at = parse_instant(&marker.t).map_err(|e| ctx(format!("figure marker: {e}")))?;
        if at < first || at > last {
            return Err(ctx(format!(
                "figure marker {:?} is outside the plotted range",
                marker.t
            )));
        }
    }
    Ok(())
}

/// Whether `slug` is non-empty kebab-case: lowercase ASCII alphanumerics and
/// single interior dashes.
fn is_kebab_slug(slug: &str) -> bool {
    !slug.is_empty()
        && !slug.starts_with('-')
        && !slug.ends_with('-')
        && !slug.contains("--")
        && slug
            .chars()
            .all(|c| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '-')
}

/// Validate one finding's content invariants. `file_stem` is the JSON
/// filename without extension; it must equal the declared slug so the corpus
/// stays greppable by slug. Returns a message naming the file and rule.
fn validate_finding(file_stem: &str, f: &Finding) -> Result<(), String> {
    let ctx = |msg: String| format!("data/findings/{file_stem}.json: {msg}");

    if !is_kebab_slug(&f.slug) {
        return Err(ctx(format!("slug {:?} is not kebab-case", f.slug)));
    }
    if f.slug != file_stem {
        return Err(ctx(format!(
            "slug {:?} does not match the filename",
            f.slug
        )));
    }

    for (label, value) in [
        ("title", &f.title),
        ("summary", &f.summary),
        ("body", &f.body),
    ] {
        if value.trim().is_empty() {
            return Err(ctx(format!("empty {label}")));
        }
    }

    let observed_at = parse_date(&f.observed_at).map_err(|e| ctx(format!("observed_at: {e}")))?;
    let published_at =
        parse_date(&f.published_at).map_err(|e| ctx(format!("published_at: {e}")))?;
    if published_at < observed_at {
        return Err(ctx(format!(
            "published_at {} precedes observed_at {}",
            f.published_at, f.observed_at
        )));
    }
    if let Some(until) = &f.observed_until {
        let observed_until = parse_date(until).map_err(|e| ctx(format!("observed_until: {e}")))?;
        if observed_until < observed_at {
            return Err(ctx(format!(
                "observed_until {until} precedes observed_at {}",
                f.observed_at
            )));
        }
    }

    let source_codes: BTreeSet<&str> = SOURCE_REGISTRY.iter().map(|s| s.code).collect();
    if f.affected_sources.is_empty() {
        return Err(ctx("affected_sources must name at least one source".into()));
    }
    let mut seen_sources = BTreeSet::new();
    for code in &f.affected_sources {
        if !source_codes.contains(code.as_str()) {
            return Err(ctx(format!(
                "affected_sources {code:?} is not a registered source code"
            )));
        }
        if !seen_sources.insert(code.as_str()) {
            return Err(ctx(format!("duplicate affected_sources entry {code:?}")));
        }
    }

    for anchor in &f.anchors {
        match anchor.kind {
            AnchorKind::BtcHeight | AnchorKind::ChildHeight => {
                if anchor.value.parse::<i64>().map_or(true, |h| h <= 0) {
                    return Err(ctx(format!(
                        "height anchor value {:?} is not a positive integer",
                        anchor.value
                    )));
                }
            }
            AnchorKind::Source => {
                if !source_codes.contains(anchor.value.as_str()) {
                    return Err(ctx(format!(
                        "source anchor {:?} is not a registered source code",
                        anchor.value
                    )));
                }
            }
            AnchorKind::Pool => {
                if anchor.value.trim().is_empty() {
                    return Err(ctx("empty pool anchor value".into()));
                }
            }
        }
        if let Some(label) = &anchor.label
            && label.trim().is_empty()
        {
            return Err(ctx(format!("anchor {:?} has an empty label", anchor.value)));
        }
    }

    for figure in &f.figures {
        validate_figure(&ctx, figure)?;
    }

    validate_finding_citations(&ctx, f)
}

/// Citation integrity: at least one reference (every article renders a
/// Sources section), unique positive ids, http urls, non-empty labels, every
/// `[^N]` marker in `summary`/`body` resolves, and no orphan references.
fn validate_finding_citations(ctx: &impl Fn(String) -> String, f: &Finding) -> Result<(), String> {
    if f.references.is_empty() {
        return Err(ctx("references must contain at least one entry".into()));
    }
    let mut ref_ids: BTreeSet<u32> = BTreeSet::new();
    for r in &f.references {
        if r.id == 0 {
            return Err(ctx("reference id must be > 0".into()));
        }
        if !ref_ids.insert(r.id) {
            return Err(ctx(format!("duplicate reference id {}", r.id)));
        }
        if r.label.trim().is_empty() {
            return Err(ctx(format!("reference {} has an empty label", r.id)));
        }
        if !(r.url.starts_with("http://") || r.url.starts_with("https://")) {
            return Err(ctx(format!(
                "reference {} url must start with http:// or https://",
                r.id
            )));
        }
    }
    let mut cited: BTreeSet<u32> = BTreeSet::new();
    for text in [&f.summary, &f.body] {
        for id in citation_ids(text) {
            if !ref_ids.contains(&id) {
                return Err(ctx(format!("citation [^{id}] has no matching reference")));
            }
            cited.insert(id);
        }
    }
    for r in &f.references {
        if !cited.contains(&r.id) {
            return Err(ctx(format!(
                "reference {} is declared but never cited",
                r.id
            )));
        }
    }
    Ok(())
}

/// Read, validate, and sort the findings corpus from `dir` (one `.json` file
/// per finding). Panics on any invalid file (caught by tests + surfaced by
/// the gen binary), the same failure surface as `load_chain_profiles`.
/// Sorting is newest-first: `observed_at` descending, slug ascending on ties,
/// so the generated module needs no frontend re-sort.
pub fn load_findings(dir: &Path) -> Vec<Finding> {
    let mut findings: Vec<Finding> = Vec::new();
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|err| panic!("read findings dir {}: {err}", dir.display()))
        .map(|entry| entry.expect("readable findings dir entry").path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "json"))
        .collect();
    entries.sort();
    assert!(
        !entries.is_empty(),
        "findings dir {} contains no .json files",
        dir.display()
    );

    let mut slugs: BTreeSet<String> = BTreeSet::new();
    for path in entries {
        let file_stem = path
            .file_stem()
            .and_then(|stem| stem.to_str())
            .unwrap_or_else(|| panic!("non-UTF-8 findings filename {}", path.display()))
            .to_owned();
        let raw = std::fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
        let finding: Finding = serde_json::from_str(&raw)
            .unwrap_or_else(|err| panic!("data/findings/{file_stem}.json: {err}"));
        if let Err(msg) = validate_finding(&file_stem, &finding) {
            panic!("{msg}");
        }
        assert!(
            slugs.insert(finding.slug.clone()),
            "data/findings/{file_stem}.json: duplicate slug {:?}",
            finding.slug
        );
        findings.push(finding);
    }

    findings.sort_by(|a, b| {
        let a_date = parse_date(&a.observed_at).expect("validated date");
        let b_date = parse_date(&b.observed_at).expect("validated date");
        b_date.cmp(&a_date).then_with(|| a.slug.cmp(&b.slug))
    });
    findings
}

/// Render `www/js/findings.generated.js`: the corpus as one `FINDINGS` array
/// export, newest-first. Serialized through serde so escaping is correct;
/// input order is already deterministic from [`load_findings`].
pub fn render_findings_js(findings: &[Finding]) -> String {
    let mut out = String::new();
    for line in GENERATED_BANNER.lines() {
        out.push_str("// ");
        out.push_str(line);
        out.push('\n');
    }
    out.push('\n');
    let body = serde_json::to_string_pretty(findings).expect("findings serialize");
    out.push_str(&format!("export const FINDINGS = {body};\n"));
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The committed corpus directory, resolved from this crate's manifest dir
    /// (the same repo-root-relative convention as the source-registry drift
    /// gate).
    fn repo_findings_dir() -> std::path::PathBuf {
        std::path::PathBuf::from(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../",
            "data/findings"
        ))
    }

    fn valid_finding_json() -> serde_json::Value {
        serde_json::json!({
            "slug": "test-finding",
            "title": "A test finding",
            "category": "dataset-note",
            "status": "concluded",
            "observed_at": "2026-06-10",
            "published_at": "2026-07-29",
            "affected_sources": ["auxpow:hathor"],
            "summary": "Summary prose.[^1]",
            "body": "Body prose.\n\nSecond paragraph.",
            "anchors": [
                { "kind": "btc-height", "value": "953043" },
                { "kind": "source", "value": "auxpow:hathor" }
            ],
            "references": [
                { "id": 1, "label": "Example", "url": "https://example.com" }
            ]
        })
    }

    fn parse(value: serde_json::Value) -> Finding {
        serde_json::from_value(value).expect("test finding parses")
    }

    fn expect_err(value: serde_json::Value, needle: &str) {
        let finding = parse(value);
        let err = validate_finding("test-finding", &finding).expect_err("validation must fail");
        assert!(
            err.contains(needle),
            "error {err:?} must contain {needle:?}"
        );
    }

    #[test]
    fn valid_finding_passes() {
        let finding = parse(valid_finding_json());
        validate_finding("test-finding", &finding).expect("valid finding");
    }

    #[test]
    fn unknown_field_fails_parse() {
        let mut v = valid_finding_json();
        v["surprise"] = serde_json::json!(true);
        assert!(serde_json::from_value::<Finding>(v).is_err());
    }

    #[test]
    fn slug_filename_mismatch_is_rejected() {
        let finding = parse(valid_finding_json());
        let err = validate_finding("other-name", &finding).expect_err("must fail");
        assert!(err.contains("does not match the filename"), "{err}");
    }

    #[test]
    fn non_kebab_slug_is_rejected() {
        let mut v = valid_finding_json();
        v["slug"] = serde_json::json!("Bad_Slug");
        let finding = parse(v);
        let err = validate_finding("Bad_Slug", &finding).expect_err("must fail");
        assert!(err.contains("not kebab-case"), "{err}");
    }

    #[test]
    fn empty_render_critical_fields_are_rejected() {
        for field in ["title", "summary", "body"] {
            let mut v = valid_finding_json();
            v[field] = serde_json::json!("   ");
            expect_err(v, &format!("empty {field}"));
        }
    }

    #[test]
    fn impossible_calendar_date_is_rejected() {
        let mut v = valid_finding_json();
        v["observed_at"] = serde_json::json!("2026-02-30");
        expect_err(v, "invalid calendar date");
    }

    #[test]
    fn observed_until_before_observed_at_is_rejected() {
        let mut v = valid_finding_json();
        v["observed_until"] = serde_json::json!("2026-06-09");
        expect_err(v, "precedes observed_at");
    }

    #[test]
    fn empty_affected_sources_is_rejected() {
        let mut v = valid_finding_json();
        v["affected_sources"] = serde_json::json!([]);
        expect_err(v, "at least one source");
    }

    #[test]
    fn unknown_affected_source_is_rejected() {
        let mut v = valid_finding_json();
        v["affected_sources"] = serde_json::json!(["auxpow:nope"]);
        expect_err(v, "not a registered source code");
    }

    #[test]
    fn duplicate_affected_source_is_rejected() {
        let mut v = valid_finding_json();
        v["affected_sources"] = serde_json::json!(["auxpow:hathor", "auxpow:hathor"]);
        expect_err(v, "duplicate affected_sources");
    }

    #[test]
    fn non_positive_height_anchor_is_rejected() {
        for bad in ["0", "-5", "12.5", "tall"] {
            let mut v = valid_finding_json();
            v["anchors"] = serde_json::json!([{ "kind": "btc-height", "value": bad }]);
            expect_err(v, "not a positive integer");
        }
    }

    #[test]
    fn unknown_source_anchor_is_rejected() {
        let mut v = valid_finding_json();
        v["anchors"] = serde_json::json!([{ "kind": "source", "value": "auxpow:nope" }]);
        expect_err(v, "not a registered source code");
    }

    #[test]
    fn empty_pool_anchor_value_is_rejected() {
        let mut v = valid_finding_json();
        v["anchors"] = serde_json::json!([{ "kind": "pool", "value": " " }]);
        expect_err(v, "empty pool anchor value");
    }

    #[test]
    fn empty_anchor_label_is_rejected() {
        let mut v = valid_finding_json();
        v["anchors"] = serde_json::json!([
            { "kind": "btc-height", "value": "953043", "label": "  " }
        ]);
        expect_err(v, "empty label");
    }

    fn valid_figure_json() -> serde_json::Value {
        serde_json::json!({
            "kind": "line-series",
            "caption": "Test series",
            "y_label": "value",
            "points": [
                { "t": "2026-06-01", "v": 1.0 },
                { "t": "2026-06-10T12:00", "v": 2.0 }
            ],
            "markers": [{ "t": "2026-06-05", "label": "event" }],
            "note": "test data"
        })
    }

    #[test]
    fn valid_figure_passes() {
        let mut v = valid_finding_json();
        v["figures"] = serde_json::json!([valid_figure_json()]);
        let finding = parse(v);
        validate_finding("test-finding", &finding).expect("valid figure");
    }

    #[test]
    fn single_point_figure_is_rejected() {
        let mut fig = valid_figure_json();
        fig["points"] = serde_json::json!([{ "t": "2026-06-01", "v": 1.0 }]);
        let mut v = valid_finding_json();
        v["figures"] = serde_json::json!([fig]);
        expect_err(v, "at least two points");
    }

    #[test]
    fn unsorted_figure_points_are_rejected() {
        let mut fig = valid_figure_json();
        fig["points"] = serde_json::json!([
            { "t": "2026-06-10", "v": 1.0 },
            { "t": "2026-06-01", "v": 2.0 }
        ]);
        let mut v = valid_finding_json();
        v["figures"] = serde_json::json!([fig]);
        expect_err(v, "strictly increasing");
    }

    #[test]
    fn out_of_range_figure_marker_is_rejected() {
        let mut fig = valid_figure_json();
        fig["markers"] = serde_json::json!([{ "t": "2026-07-01", "label": "late" }]);
        let mut v = valid_finding_json();
        v["figures"] = serde_json::json!([fig]);
        expect_err(v, "outside the plotted range");
    }

    #[test]
    fn malformed_figure_instant_is_rejected() {
        let mut fig = valid_figure_json();
        fig["points"][0]["t"] = serde_json::json!("June 1st");
        let mut v = valid_finding_json();
        v["figures"] = serde_json::json!([fig]);
        expect_err(v, "invalid instant");
    }

    #[test]
    fn missing_references_are_rejected() {
        let mut v = valid_finding_json();
        v["references"] = serde_json::json!([]);
        v["summary"] = serde_json::json!("No citations.");
        expect_err(v, "at least one entry");
    }

    #[test]
    fn unresolved_citation_is_rejected() {
        let mut v = valid_finding_json();
        v["body"] = serde_json::json!("Claims things.[^9]");
        expect_err(v, "[^9] has no matching reference");
    }

    #[test]
    fn orphan_reference_is_rejected() {
        let mut v = valid_finding_json();
        v["references"] = serde_json::json!([
            { "id": 1, "label": "Example", "url": "https://example.com" },
            { "id": 2, "label": "Unused", "url": "https://example.com/2" }
        ]);
        expect_err(v, "reference 2 is declared but never cited");
    }

    #[test]
    fn non_http_reference_url_is_rejected() {
        // "httpss://" is the sneaky case: a bare starts_with("http") accepts it.
        for bad in ["ftp://example.com", "httpss://example.com", "example.com"] {
            let mut v = valid_finding_json();
            v["references"] = serde_json::json!([{ "id": 1, "label": "Example", "url": bad }]);
            expect_err(v, "url must start with http:// or https://");
        }
    }

    #[test]
    fn published_before_observed_is_rejected() {
        let mut v = valid_finding_json();
        v["published_at"] = serde_json::json!("2026-06-09");
        expect_err(v, "precedes observed_at");
    }

    #[test]
    fn corpus_loads_sorted_newest_first() {
        let findings = load_findings(&repo_findings_dir());
        assert!(!findings.is_empty(), "seed corpus present");
        let dates: Vec<Date> = findings
            .iter()
            .map(|f| parse_date(&f.observed_at).expect("validated date"))
            .collect();
        for pair in dates.windows(2) {
            assert!(pair[0] >= pair[1], "corpus is sorted newest-first");
        }
    }

    #[test]
    fn render_is_deterministic_and_exports_findings() {
        let findings = load_findings(&repo_findings_dir());
        let js = render_findings_js(&findings);
        assert_eq!(
            js,
            render_findings_js(&findings),
            "generation must be deterministic"
        );
        assert!(js.starts_with("// GENERATED"), "banner present");
        assert!(js.contains("data/findings/"), "banner names the data dir");
        assert!(js.contains("export const FINDINGS = ["), "array export");
    }

    #[test]
    fn committed_findings_match_data() {
        // The committed artifact MUST equal the generator output. This wires
        // the --check drift gate into standard `cargo test`, exactly like
        // `committed_artifacts_match_registry`. If this fails, run
        // `just gen-source-artifacts`.
        let root = concat!(env!("CARGO_MANIFEST_DIR"), "/../..");
        let js = std::fs::read_to_string(format!("{root}/{FINDINGS_JS_PATH}"))
            .expect("read committed findings JS");
        let findings = load_findings(&repo_findings_dir());
        assert_eq!(
            js,
            render_findings_js(&findings),
            "{FINDINGS_JS_PATH} drift; run `just gen-source-artifacts`"
        );
    }
}
