//! Offline BTC nBits-by-DAA-epoch table and contamination verdict.
//!
//! Shared facility for the public-RPC producers (Hathor and Elastos). A
//! merge-mined parent header that satisfies its own
//! encoded target is not necessarily a BTC block: BCH/BSV-family headers pass
//! their easier target while sharing a BTC ancestor. This table records the
//! canonical BTC nBits at each 2016-block retarget boundary, so a parent's nBits
//! at its BIP34 height can be checked offline (no Bitcoin Core RPC) against what
//! BTC actually used, rejecting contaminants.
//!
//! Residual limit: the check indexes the table by the parent's own BIP34
//! coinbase height, so a contaminant is rejected only when its nBits differs from
//! BTC's at that epoch. A BCH/BSV parent whose nBits happens to be bit-identical
//! to BTC's at the same epoch is indistinguishable by PoW alone and would pass;
//! this is the documented trust boundary of the offline check, not a defect.
//! Post-fork BTC/BCH difficulties diverge, so a same-epoch collision is rare.
//!
//! The embedded table is the fast in-range path and the offline-backfill / test
//! seed; it is regenerated by `scripts/gen-nbits-table.py` (Bitcoin Core
//! `getblockheader` at each epoch boundary) and carries its covered min/max
//! height. It no longer has to track the BTC tip: a live producer whose parent is
//! beyond the horizon ([`NbitsVerdict::AboveTableHorizon`]) resolves the canonical
//! epoch nBits from Bitcoin Core at runtime
//! (`mmm-producers::chains::nbits_horizon`), so offline capture still runs on only
//! the in-range path while live capture advances past the horizon without a regen.
//! The read-model BTC orphan classifier (`btc_orphan`) and the API tree-anchor
//! still read this table directly and degrade above-horizon rows to pending /
//! unplaced, so a freshness floor is kept for them (see the tests).

use std::collections::HashMap;
use std::sync::LazyLock;

use bitcoin::CompactTarget;
use serde::Deserialize;

const TABLE_JSON: &str = include_str!("../../../data/consensus/btc_nbits_by_epoch.json");

/// The Bitcoin difficulty-adjustment (DAA) retarget interval, in blocks. The
/// canonical 2016 is fixed consensus; the embedded table's `epoch_interval` must
/// equal it (asserted in tests). Used by [`daa_epoch_start`] so the Core-backed
/// runtime resolver derives epoch boundaries without the embedded table.
pub const DAA_EPOCH_INTERVAL: i32 = 2016;

/// JSON deserialization schema of the embedded `btc_nbits_by_epoch.json`
/// (produced by `scripts/gen-nbits-table.py`). Map keys/values are the
/// generator's native form: epoch keys are decimal-string heights and nBits
/// values are compact-target hex; `parse` narrows them to `i32`/`u32`. The
/// `serde(default)` time fields keep an older committed table (without the weak
/// time lookup) parseable, so weak classification degrades to `NoTimeTable`
/// rather than silently misclassifying.
#[derive(Debug, Deserialize)]
struct RawTable {
    epoch_interval: i32,
    covered_min_height: i32,
    covered_max_height: i32,
    nbits_by_epoch: HashMap<String, String>,
    // Weak-classification time lookup. Optional so an older committed table
    // without these fields still parses; weak then degrades to "insufficient"
    // (NoTimeTable) rather than silently misclassifying. Regenerate with
    // `scripts/gen-nbits-table.py` to populate them.
    #[serde(default)]
    covered_max_time: Option<i64>,
    #[serde(default)]
    time_by_epoch: HashMap<String, i64>,
}

/// The parsed, embedded BTC nBits-by-epoch table.
#[derive(Debug)]
pub struct NbitsTable {
    epoch_interval: i32,
    covered_min_height: i32,
    covered_max_height: i32,
    by_epoch: HashMap<i32, u32>,
    /// Upper time bound of the latest (partial) covered epoch: the generation
    /// tip header's time. `None` when the committed table predates the weak
    /// time lookup. A header time above this is treated as pending (the table
    /// is stale for that row), not excluded.
    covered_max_time: Option<i64>,
    /// `(epoch_start_time, epoch_height)` sorted ascending by time, for
    /// bisecting a header timestamp to its covering epoch (built from the
    /// table's per-epoch first-block times).
    epochs_by_time: Vec<(i64, i32)>,
}

/// Result of an expected-nBits lookup at a BTC height.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NbitsLookup {
    /// The canonical BTC nBits (compact form) for this height's epoch.
    Found(u32),
    /// The height is below the table's covered minimum.
    BelowTable,
    /// The height is beyond the table's covered maximum (stale table).
    AboveTable,
}

/// Offline contamination verdict for a reconstructed parent header.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NbitsVerdict {
    /// The parent nBits matches the canonical BTC nBits at its BIP34 height.
    Valid,
    /// The parent nBits differs from BTC's (a BCH/BSV contaminant or fabrication).
    Contaminant,
    /// No usable BIP34 height, or a height below the table minimum.
    Indeterminate,
    /// A BIP34 height beyond the table horizon: a stale-table condition that
    /// must pin/abort the poller rather than silently skip future valid rows.
    AboveTableHorizon,
}

impl NbitsTable {
    /// Build the in-memory table, deriving `epochs_by_time` as an ascending
    /// `(epoch_start_time, epoch_height)` index from `time_by_epoch` so a header
    /// timestamp can be bisected to its covering epoch. Sole constructor behind
    /// both `parse` (embedded JSON) and `from_test_parts` (test fixtures).
    fn new(
        epoch_interval: i32,
        covered_min_height: i32,
        covered_max_height: i32,
        covered_max_time: Option<i64>,
        by_epoch: HashMap<i32, u32>,
        time_by_epoch: &HashMap<i32, i64>,
    ) -> Self {
        let mut epochs_by_time: Vec<(i64, i32)> =
            time_by_epoch.iter().map(|(&h, &t)| (t, h)).collect();
        epochs_by_time.sort_unstable();
        Self {
            epoch_interval,
            covered_min_height,
            covered_max_height,
            by_epoch,
            covered_max_time,
            epochs_by_time,
        }
    }

    /// Parse the `include_str!`-embedded `btc_nbits_by_epoch.json` into the
    /// table. Narrows the JSON's string epoch keys (decimal heights) and hex
    /// nBits values (compact-target form) to `i32`/`u32`. Panics on malformed
    /// embedded data: the JSON is a committed build artifact regenerated by
    /// `scripts/gen-nbits-table.py`, so a parse failure is a build defect, not a
    /// runtime condition. Runs once behind the `TABLE` `LazyLock`.
    fn parse() -> Self {
        let raw: RawTable =
            serde_json::from_str(TABLE_JSON).expect("embedded btc_nbits_by_epoch.json is valid");
        let by_epoch = raw
            .nbits_by_epoch
            .iter()
            .map(|(epoch, bits)| {
                let epoch = epoch
                    .parse::<i32>()
                    .expect("embedded nBits epoch key is an i32");
                let bits =
                    u32::from_str_radix(bits, 16).expect("embedded nBits value is compact hex");
                (epoch, bits)
            })
            .collect();
        let time_by_epoch: HashMap<i32, i64> = raw
            .time_by_epoch
            .iter()
            .map(|(epoch, time)| {
                let epoch = epoch
                    .parse::<i32>()
                    .expect("embedded nBits time epoch key is an i32");
                (epoch, *time)
            })
            .collect();
        Self::new(
            raw.epoch_interval,
            raw.covered_min_height,
            raw.covered_max_height,
            raw.covered_max_time,
            by_epoch,
            &time_by_epoch,
        )
    }

    /// Construct a table from explicit fixture slices, bypassing the embedded
    /// JSON, so weak/strict classification edge cases (partial latest epoch,
    /// floor/horizon bounds) can be unit-tested deterministically. Test-only
    /// (`#[cfg(test)]`).
    #[cfg(test)]
    pub(crate) fn from_test_parts(
        epoch_interval: i32,
        covered_min_height: i32,
        covered_max_height: i32,
        covered_max_time: Option<i64>,
        by_epoch: &[(i32, u32)],
        time_by_epoch: &[(i32, i64)],
    ) -> Self {
        Self::new(
            epoch_interval,
            covered_min_height,
            covered_max_height,
            covered_max_time,
            by_epoch.iter().copied().collect(),
            &time_by_epoch.iter().copied().collect(),
        )
    }

    /// Highest BTC height whose epoch the table covers (the table covers up to
    /// `covered_max_height + epoch_interval - 1`).
    pub fn covered_max_height(&self) -> i32 {
        self.covered_max_height
    }

    /// Expected canonical BTC nBits (compact) for `height`, by its DAA epoch.
    pub fn expected_nbits(&self, height: i32) -> NbitsLookup {
        if height < self.covered_min_height {
            return NbitsLookup::BelowTable;
        }
        let epoch = (height / self.epoch_interval) * self.epoch_interval;
        if epoch > self.covered_max_height {
            return NbitsLookup::AboveTable;
        }
        match self.by_epoch.get(&epoch) {
            Some(&bits) => NbitsLookup::Found(bits),
            None => NbitsLookup::AboveTable,
        }
    }

    /// The 2016-block DAA epoch interval.
    pub fn epoch_interval(&self) -> i32 {
        self.epoch_interval
    }

    /// Upper time bound of the latest covered (partial) epoch: the generation
    /// tip header's time. `None` when the committed table predates the weak
    /// time lookup; a header time above this is pending, not excluded.
    pub fn covered_max_time(&self) -> Option<i64> {
        self.covered_max_time
    }

    /// Whether the table carries the weak-classification time lookup
    /// (`time_by_epoch` + `covered_max_time`). False for an un-regenerated
    /// committed table; the strict path then skips its time-epoch guard and weak
    /// degrades to insufficient.
    pub fn has_time_table(&self) -> bool {
        self.covered_max_time.is_some() && !self.epochs_by_time.is_empty()
    }

    /// The epoch-boundary height whose covered time window contains `time`, or
    /// `None` when there is no time table, `time` precedes the earliest epoch,
    /// or `time` is beyond `covered_max_time`.
    pub fn epoch_height_for_time(&self, time: i64) -> Option<i32> {
        let covered_max_time = self.covered_max_time?;
        if self.epochs_by_time.is_empty()
            || time < self.epochs_by_time[0].0
            || time > covered_max_time
        {
            return None;
        }
        // `partition_point` returns the count of leading entries with start time
        // <= `time`; that count is >= 1 because `time >= epochs_by_time[0].0`,
        // so `idx - 1` indexes the covering epoch.
        let idx = self.epochs_by_time.partition_point(|&(t, _)| t <= time);
        self.epochs_by_time.get(idx - 1).map(|&(_, height)| height)
    }

    /// BTC nBits at the timestamp-selected epoch and its EXACT +/-1 retarget
    /// neighbors (`epoch +/- epoch_interval`), using only neighbor epochs
    /// actually present in the table (sparse-neighbor guard).
    fn allowed_bits_pm1(&self, epoch_height: i32) -> [Option<u32>; 3] {
        [
            self.by_epoch
                .get(&(epoch_height - self.epoch_interval))
                .copied(),
            self.by_epoch.get(&epoch_height).copied(),
            self.by_epoch
                .get(&(epoch_height + self.epoch_interval))
                .copied(),
        ]
    }

    /// Weak (timestamp-epoch) nBits classification: bisect `header_time` to its
    /// covering epoch and accept `actual_bits` if it equals that epoch's nBits or
    /// an exact +/-1 retarget neighbor (the weak path's looser, timestamp-keyed
    /// check used when no trustworthy BIP34 height is available). Guard ordering
    /// is the contract: no time table -> `NoTimeTable`; below the earliest
    /// covered epoch -> `BelowFloor`; above `covered_max_time` -> `AboveHorizon`
    /// (pending, a stale table, not an exclusion); otherwise `Match` /
    /// `NonBtcEpochBits`. `actual_bits` is compared via `to_consensus` (compact
    /// form), never reversed.
    pub fn classify_nbits_by_time(
        &self,
        header_time: i64,
        actual_bits: CompactTarget,
    ) -> WeakVerdict {
        let Some(covered_max_time) = self.covered_max_time else {
            return WeakVerdict::NoTimeTable;
        };
        if self.epochs_by_time.is_empty() {
            return WeakVerdict::NoTimeTable;
        }
        if header_time < self.epochs_by_time[0].0 {
            return WeakVerdict::BelowFloor;
        }
        if header_time > covered_max_time {
            return WeakVerdict::AboveHorizon;
        }
        let Some(epoch_height) = self.epoch_height_for_time(header_time) else {
            return WeakVerdict::BelowFloor;
        };
        let target = actual_bits.to_consensus();
        if self
            .allowed_bits_pm1(epoch_height)
            .into_iter()
            .flatten()
            .any(|bits| bits == target)
        {
            WeakVerdict::Match
        } else {
            WeakVerdict::NonBtcEpochBits
        }
    }

    /// Strict (BIP34-height-epoch) nBits classification for a reconstructed
    /// parent header. `None` height -> `Indeterminate`; below the table floor ->
    /// `Indeterminate`; above the table horizon -> `AboveTableHorizon` (the
    /// must-abort-the-poller staleness signal, never silently skipped);
    /// otherwise `Valid` when the parent's nBits equals the canonical BTC nBits
    /// at its DAA epoch, else `Contaminant`. `actual_bits` is compared via
    /// `to_consensus` (compact form); no hash/byte reversal is involved.
    pub fn classify_nbits(
        &self,
        bip34_height: Option<i32>,
        actual_bits: CompactTarget,
    ) -> NbitsVerdict {
        let Some(height) = bip34_height else {
            return NbitsVerdict::Indeterminate;
        };
        match self.expected_nbits(height) {
            NbitsLookup::AboveTable => NbitsVerdict::AboveTableHorizon,
            NbitsLookup::BelowTable => NbitsVerdict::Indeterminate,
            NbitsLookup::Found(expected) => classify_against_expected_nbits(expected, actual_bits),
        }
    }
}

static TABLE: LazyLock<NbitsTable> = LazyLock::new(NbitsTable::parse);

/// The embedded BTC nBits-by-epoch table (parsed once).
pub fn table() -> &'static NbitsTable {
    &TABLE
}

/// Strict nBits classification against the embedded table singleton (thin
/// `table().classify_nbits(..)` convenience for callers that do not already
/// hold an `&NbitsTable`). See [`NbitsTable::classify_nbits`] for the
/// verdict-mapping and the `AboveTableHorizon` must-abort contract.
pub fn classify_nbits(bip34_height: Option<i32>, actual_bits: CompactTarget) -> NbitsVerdict {
    table().classify_nbits(bip34_height, actual_bits)
}

/// The DAA epoch-start height covering `height`: `height` rounded down to a
/// multiple of [`DAA_EPOCH_INTERVAL`]. The runtime Core-backed resolver fetches
/// the canonical BTC nBits at this boundary height when a parent is beyond the
/// embedded table's horizon.
pub fn daa_epoch_start(height: i32) -> i32 {
    (height / DAA_EPOCH_INTERVAL) * DAA_EPOCH_INTERVAL
}

/// Compare a runtime-resolved expected BTC nBits against a parent's actual nBits,
/// yielding [`NbitsVerdict::Valid`] on a match and [`NbitsVerdict::Contaminant`]
/// otherwise. The compact (`to_consensus`) forms are compared directly; no
/// hash/byte reversal is involved. This is the same comparison
/// [`NbitsTable::classify_nbits`] performs for an in-table height, factored so the
/// Core-resolved beyond-horizon path reuses it without the embedded table.
pub fn classify_against_expected_nbits(expected: u32, actual: CompactTarget) -> NbitsVerdict {
    if expected == actual.to_consensus() {
        NbitsVerdict::Valid
    } else {
        NbitsVerdict::Contaminant
    }
}

/// Weak-path verdict: timestamp-epoch nBits classification.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WeakVerdict {
    /// `actual_bits` matches the timestamp-selected epoch or an exact +/-1
    /// retarget neighbor.
    Match,
    /// The timestamp resolves to a covered epoch but `actual_bits` is not in the
    /// +/-1 retarget set.
    NonBtcEpochBits,
    /// The header time precedes the earliest covered epoch (a real BTC header
    /// cannot predate genesis): insufficient evidence.
    BelowFloor,
    /// The header time is beyond `covered_max_time`: the committed table is
    /// stale for this row. The orphan classifier routes this to pending.
    AboveHorizon,
    /// No time table is present (older committed table): insufficient cache.
    NoTimeTable,
}

/// Weak nBits classification against the embedded table singleton (thin
/// `table().classify_nbits_by_time(..)` convenience). Test-only:
/// `#[cfg(any(test, feature = "test-support"))]`. The production weak path
/// (`btc_orphan`) calls `NbitsTable::classify_nbits_by_time` on a table it
/// already holds, so this free wrapper has no production caller; see that
/// method for the guard-ordering contract.
#[cfg(any(test, feature = "test-support"))]
pub fn classify_nbits_by_time(header_time: i64, actual_bits: CompactTarget) -> WeakVerdict {
    table().classify_nbits_by_time(header_time, actual_bits)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bits(hex: &str) -> CompactTarget {
        CompactTarget::from_consensus(u32::from_str_radix(hex, 16).unwrap())
    }

    #[test]
    fn table_loads_and_classifies_in_range_heights() {
        let t = table();
        // Genesis epoch is the easiest target.
        assert_eq!(t.expected_nbits(0), NbitsLookup::Found(0x1d00_ffff));
        // The embedded table is the offline / in-range path; it no longer has to
        // track the BTC tip, because a live parent beyond its horizon is resolved
        // from Bitcoin Core at runtime (see `mmm-producers` `nbits_horizon`). So
        // there is no pre-deploy "must cover the tip" floor here. Spot-check an
        // in-range epoch: the historical Elastos parent at 953,569 (epoch 953,568,
        // nBits 170240c3) still classifies Valid against the committed table.
        const IN_RANGE_PARENT_HEIGHT: i32 = 953_569;
        const IN_RANGE_PARENT_NBITS: u32 = 0x1702_40c3;
        assert_eq!(
            t.expected_nbits(IN_RANGE_PARENT_HEIGHT),
            NbitsLookup::Found(IN_RANGE_PARENT_NBITS)
        );
        assert_eq!(
            classify_nbits(
                Some(IN_RANGE_PARENT_HEIGHT),
                CompactTarget::from_consensus(IN_RANGE_PARENT_NBITS)
            ),
            NbitsVerdict::Valid
        );
    }

    #[test]
    fn daa_epoch_start_rounds_down_to_retarget_boundary() {
        assert_eq!(daa_epoch_start(0), 0);
        assert_eq!(daa_epoch_start(2015), 0);
        assert_eq!(daa_epoch_start(2016), 2016);
        // The Elastos live-stall parent 955,585 sits in epoch 955,584.
        assert_eq!(daa_epoch_start(955_585), 955_584);
        assert_eq!(daa_epoch_start(953_569), 953_568);
    }

    #[test]
    fn embedded_table_epoch_interval_is_the_daa_constant() {
        assert_eq!(table().epoch_interval(), DAA_EPOCH_INTERVAL);
    }

    #[test]
    fn classify_against_expected_nbits_matches_and_mismatches() {
        const EXPECTED: u32 = 0x1702_40c3;
        assert_eq!(
            classify_against_expected_nbits(EXPECTED, bits("170240c3")),
            NbitsVerdict::Valid
        );
        // A BCH-shaped easier nBits at the same epoch is a contaminant.
        assert_eq!(
            classify_against_expected_nbits(EXPECTED, bits("1a0fffff")),
            NbitsVerdict::Contaminant
        );
    }

    #[test]
    fn embedded_table_freshness_floor_guards_read_model_consumers() {
        // The live producers resolve beyond-horizon nBits from Bitcoin Core, so they
        // no longer need the embedded table to track the tip. But the read-model BTC
        // orphan classifier (`mmm-capture::btc_orphan`) and the API tree-anchor
        // placement (`mmm-api`'s `orphan_component`) still read this table directly
        // and degrade recent above-horizon rows to pending / unplaced. With the
        // producer regen-pressure gone, keep a pre-deploy floor so a committed table
        // that regressed (or a rebuild against a stale table) fails here; raise the
        // floor on every `scripts/gen-nbits-table.py` regen. Remove this guard only
        // when those consumers route through the Core-backed provider.
        let t = table();
        const READ_MODEL_EPOCH_FLOOR: i32 = 953_568;
        const READ_MODEL_TIME_FLOOR: i64 = 1_781_450_452;
        assert!(
            t.covered_max_height() >= READ_MODEL_EPOCH_FLOOR,
            "nBits table horizon {} regressed below the read-model floor {}; regenerate scripts/gen-nbits-table.py",
            t.covered_max_height(),
            READ_MODEL_EPOCH_FLOOR
        );
        if let Some(covered_max_time) = t.covered_max_time() {
            assert!(
                covered_max_time >= READ_MODEL_TIME_FLOOR,
                "nBits time horizon {covered_max_time} regressed below the read-model floor {READ_MODEL_TIME_FLOOR}; regenerate scripts/gen-nbits-table.py",
            );
        }
    }

    #[test]
    fn validated_stale_fixtures_classify_valid() {
        // Cross-check the embedded table against the 6 validated-stale fixtures:
        // each parent's BIP34 height + its CSV nBits must classify as Valid.
        for json in [
            include_str!("../../../fixtures/hathor/1971823.json"),
            include_str!("../../../fixtures/hathor/2773476.json"),
            include_str!("../../../fixtures/hathor/3261131.json"),
            include_str!("../../../fixtures/hathor/4482931.json"),
            include_str!("../../../fixtures/hathor/5249647.json"),
            include_str!("../../../fixtures/hathor/6342295.json"),
        ] {
            let j: serde_json::Value = serde_json::from_str(json).unwrap();
            let height = j["expected_btc_height_bip34"].as_i64().unwrap() as i32;
            let nbits = j["expected_nbits"].as_str().unwrap();
            assert_eq!(
                classify_nbits(Some(height), bits(nbits)),
                NbitsVerdict::Valid,
                "fixture at BTC height {height} should classify Valid"
            );
        }
    }

    #[test]
    fn wrong_nbits_at_a_covered_height_is_contaminant() {
        // BTC height 710969 with a deliberately wrong (BCH-shaped, easier) nBits.
        assert_eq!(
            classify_nbits(Some(710_969), bits("1a0fffff")),
            NbitsVerdict::Contaminant
        );
    }

    #[test]
    fn height_beyond_horizon_is_above_table() {
        assert_eq!(
            classify_nbits(Some(2_000_000), bits("17000000")),
            NbitsVerdict::AboveTableHorizon
        );
    }

    #[test]
    fn no_bip34_height_is_indeterminate() {
        assert_eq!(
            classify_nbits(None, bits("170c69ea")),
            NbitsVerdict::Indeterminate
        );
    }

    fn easy() -> u32 {
        u32::from_str_radix("1d00ffff", 16).unwrap()
    }

    #[test]
    fn weak_is_inert_without_a_time_table() {
        // With no time lookup (`covered_max_time` None / empty time map), the weak
        // path MUST be inert (`NoTimeTable`) so it never silently misclassifies.
        // The embedded table no longer needs to track the BTC tip (beyond-horizon
        // live parents are resolved from Core at runtime), so there is no
        // time-floor assertion here.
        let t = NbitsTable::from_test_parts(2016, 0, 2016, None, &[(0, easy())], &[]);
        assert_eq!(
            t.classify_nbits_by_time(1_700_000_000, bits("170c69ea")),
            WeakVerdict::NoTimeTable
        );
    }

    #[test]
    fn time_table_covers_the_elastos_stall_epoch() {
        // BTC epoch 953,568 started at time 1,781,396,637 with nBits 170240c3.
        const ELASTOS_STALL_EPOCH_TIME: i64 = 1_781_396_637;
        assert_eq!(
            table().epoch_height_for_time(ELASTOS_STALL_EPOCH_TIME),
            Some(953_568)
        );
        assert_eq!(
            classify_nbits_by_time(ELASTOS_STALL_EPOCH_TIME, bits("170240c3")),
            WeakVerdict::Match
        );
    }

    #[test]
    fn classify_nbits_by_time_handles_partial_latest_epoch() {
        // Epoch 2016 boundary time is 2000; the latest epoch is partial up to the
        // tip bound covered_max_time = 3000.
        let t = NbitsTable::from_test_parts(
            2016,
            0,
            2016,
            Some(3000),
            &[(0, easy()), (2016, easy())],
            &[(0, 1000), (2016, 2000)],
        );
        // A timestamp after the last boundary but before the tip maps to the
        // latest epoch and is Match-eligible, not out of range.
        assert_eq!(
            t.classify_nbits_by_time(2500, bits("1d00ffff")),
            WeakVerdict::Match
        );
        // A timestamp beyond the tip bound is above the horizon (pending), and a
        // timestamp before the earliest epoch is below the floor.
        assert_eq!(
            t.classify_nbits_by_time(3500, bits("1d00ffff")),
            WeakVerdict::AboveHorizon
        );
        assert_eq!(
            t.classify_nbits_by_time(500, bits("1d00ffff")),
            WeakVerdict::BelowFloor
        );
    }

    #[test]
    fn epoch_height_for_time_bisects_and_bounds() {
        let t = NbitsTable::from_test_parts(
            2016,
            0,
            2016,
            Some(3000),
            &[(0, easy()), (2016, easy())],
            &[(0, 1000), (2016, 2000)],
        );
        assert_eq!(t.epoch_height_for_time(1000), Some(0));
        assert_eq!(t.epoch_height_for_time(1500), Some(0));
        assert_eq!(t.epoch_height_for_time(2000), Some(2016));
        assert_eq!(t.epoch_height_for_time(3000), Some(2016)); // == covered_max_time
        assert_eq!(t.epoch_height_for_time(999), None); // below floor
        assert_eq!(t.epoch_height_for_time(3001), None); // above covered_max_time
    }
}
